services:
  bot:
    image: satamanchuk/alexbot:latest
    container_name: alexbot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    env_file:
      - .env

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_ROLLING_RESTART=true
    command: alexbot
